### ISSUE TITLE
installers not working

### ISSUE THREAD

**Issue by ahraber** [budlabs/i3ass#14]
I ran `install.sh -q /home/me/i3` and the scrit ran and only made man pages. I don't have the commands available via my shell. I don't think this is expected.

Also, I'm running arch, and tried installing via AUR, and have the following error:
```
 ==> Validating source files with sha256sums...
    v.0.1.65.tar.gz ... FAILED
==> ERROR: One or more files did not pass the validity check!
Error downloading sources: i3ass
```

**Comment by budRich** [comment]
thanks for the report. I never tested the install after the last update. I will fix it right away.

**Comment by budRich** [comment]
well. I cannot reproduce the issue with install.sh. When executed with `-q` option, man pages should not be generated only scripts linked to target directory..

It might be that you didn't execute the script with the full path, also it's important that it is a lowercase `q`:  
``` text
$ git clone https://github.com/budlabs/i3ass.git
$ cd i3ass
$ ./install.sh -q ~/i3
```

Maybe it was the help screen that you are thinking about when you refer to the man page. It is printed if the arguments are wrong. I will add an error message to the screen.

**Comment by budRich** [comment]
@ahraber I have updated the repo and the AUR package. I have tested it here, and it seems to work. But it would be highly appreciated if you wanted to test it and see if it works for you, if it works, you can close this issue, or I will do it if it is inactive for a couple of days.

And thanks again for the quick report. I am quite new to AUR, didn't know i needed to generate the checksum for every release.
