### ISSUE TITLE
[i3run] problems

### ISSUE THREAD

**Issue by budRich** [budlabs/i3ass#172]
@budRich Thank you for making such an application for us, again I have detected a few problems. Again, I went back to the previous two versions and tested if the problem was really caused by this version. I do not encounter any errors in this version. Again, I would like other users to test the latest update, maybe the problems are specific to me https://github.com/budlabs/i3ass/releases/tag/2022.05.20.1 (version that worked fine for me)

After the last patch, Thunar really didn't seem to know where to position. when i try to open it gives this error

```
ERROR: Expected one of these tokens: <word>
ERROR: Your command: [con_id=] focus;
ERROR:                       ^^^^^^^^
```

When I run it by typing "thunar" in the terminal, "thunar" was not focused. (hide, bring forward, i3run features do not work)

_Originally posted by @yuceltoluyag in https://github.com/budlabs/i3ass/issues/170#issuecomment-1133833724_

**Comment by budRich** [comment]
@yuceltoluyag

I discovered an issue in i3run, but i don't get the same error message as you. 
Can you paste the exact commands you are doing? , and the output. Also, try using `--verbose` option, it might give some more clues in the output to stderr. (`i3run --verbose --instance thunar -- thunar`)

**Comment by budRich** [comment]
@yuceltoluyag

I pushed the changes but i want to wait making a release till i am at least 84% sure it will work. I made a new AUR package, [i3ass-git](https://aur.archlinux.org/packages/i3ass-git) that has the bleeding edge up to date changes always.

**Comment by yuceltoluyag** [comment]
I think there is a problem with the Github notification system, I saw what you wrote while checking by chance, sorry for my late reply.  @budRich 

```
 i3run --version
i3run - version: 0.2
updated: 2022-05-21 by budRich
```

I've tested the Verbose command before, it doesn't seem to be a problem there, but it didn't respond at all via shortcuts. Now I tried again, when I try to open it using shortcuts, it doesn't respond at all. 

```
i3run --verbose --instance thunar -- thunar
m [con_id=94311100114912] focus
94311100114912
[{"success":true}]
```
https://github.com/yuceltoluyag/dotfiles/blob/master/dotfiles/config/i3/config#L22  my config file
https://github.com/yuceltoluyag/dotfiles/blob/master/dotfiles/script/babamanager  thunarmanager

I've been using your configurations for years because your working style fits perfectly with my tastes.

**Comment by yuceltoluyag** [comment]
@budRich i tried again today and got an error like this maybe it can help you understand the problem

```
ERROR: Your command: [con_id=] focus;
ERROR:                       ^^^^^^^^
ERROR: Expected one of these tokens: <word>
ERROR: Your command: [con_id=] focus;
ERROR:                       ^^^^^^^^
ERROR: Expected one of these tokens: <word>
/usr/bin/i3run: line 373: 46427 Illegal instruction     (core dumped) nohup env "${_command[@]}" > /dev/null 2>&1
```

**Comment by budRich** [comment]
I want to fix this but first i need to reproduce the issue. Is it still `i3run --verbose --instance thunar -- thunar`? and what is the state of thunar (are you expecting a focus, a launch or a hide)?

**Comment by yuceltoluyag** [comment]
> i3run --verbose --instance thunar -- thunar

```
i3run --verbose --instance thunar -- thunar
m [con_id=94915306745104] focus
94915306745104
[{"success":true}]
```
I think I understand the problem now it's all my fault :( II typed "actionfm" instead of "launchfm" while editing the config files :( . :( .  https://github.com/budlabs/youtube/tree/master/thunar/private

Everything is working fine now (ノಠ益ಠ)ノ彡┻━┻

**Comment by budRich** [comment]
If I had a nickel for every table i've thrown, i would be able to buy a new table.
