### ISSUE TITLE
[i3fyra][i3run][i3viswiz] unexpected behaviour in overcomplicated scenarios

### ISSUE THREAD

**Issue by indeedwatson** [budlabs/i3ass#2]
Since the purpose of this script is to navigate "visually" as I understand it (a concept which I find more intuitive than the default behavior), I'd expect that no matter where I am in one container, switching left or right would switch left or right visually. Instead, when there's horizontal splits it moves to the left tab:
https://u.teknik.io/3A7lj.mp4

**Comment by budRich** [comment]
Excellent bugtesting. And yes, without the video it would be very hard to describe what's going on. It gets really tricky this focusing function with more advanced layouts like the one you demonstrate. and i think i have to rethink the whole thing to not end up with cocobananacode.  

I think i will try to make something that parses the tree from i3, and then "paints" the layout: Something like this:

AD
AE

and then say that e is where the focus currently is, the visual container to the left is A, and if direction is A focus will be moved there. The difference will be that i don't have to focus parent shanengans, and checking what kind of layout each parent has and such. And the end result should be much faster and fluent then the current script. The drawback is that the parsing and painting will be a quite complex thing to do (but absolutely not impossible).  

I will try to solve this during the weekend, but i can't promise anything. Really appreciate the feedback watson, and your rice is looking dank!

**Comment by indeedwatson** [comment]
I feel that i3 should have a more visually based experience by default (for example, one of the biggest gripes is how resizing shrinks or expands a window based on which window is focused, rather than just pressing left and having the resize go left, etc -- meaning, no matter where your focus is, the resize should be based on which direction you're pressing imo).

But I digress. This current script for now is what I feel I'm missing in the way I'm reworking my workflow, so I look forward to seeing what you manage when you have the time to look into it. Until then I'll have to `focus parent` `move left` :)

**Comment by budRich** [comment]
I made a total rewrite of pocus, ended up with a new script, it works better in every way, and use a completely different method for finding windows which is much faster and more reliable. Please let me know if you find any issues:  

https://github.com/budRich/i3ass/tree/master/i3viswiz  
https://youtu.be/ZaGaqPWy8eM  

----

regarding resizing: For floating windows i use modes, in which I *activate* and moves the corner of the ative window. For tiled windows i just use grow height/width on right/up, and shrink on left/down

**Comment by indeedwatson** [comment]
Okay this seems to be almost perfect. There is one small issue, which you don't even need to correct to make this usable, but I bring up in case you haven't noticed it:

The down direction functions weird. Up, left and right all work as expected: If I make a container with several windows in a horizontal split and repeatedly focus left, it moves left one by one and when it gets to the last one it cycles again. Same with right, and same with focus up with vertical splits.

However, if you have say 4 windows in a vertical split and you press down, no matter where you are in the split, it will go to the top window, and if you press it again, it won't move at all.

I suspect this must be some minor bug that you can fix, but I'm gonna start using this already since I mostly need it for horizontal movement.

Thanks for the good work.

**Comment by budRich** [comment]
Glad you liked it! I haven't noticed the bug you mention. But will see if i can fix it later. It might be the bar... The script currently doesn't take bars into account, so if GAPSIZE (`-g`) is to low, it might result in no action. Try adding a higher value to -g (default is 5 (which is to low, i think i will change this to titlebar height+5)), i will also try to make the script be aware of any bars/docks.  

Thanks for the report, and please let me know if you find anything else or got some new ideas.

**Comment by indeedwatson** [comment]
Okay, I killed polybar, got rid of all gaps from i3gaps, and it still persists.

However, testing the `-g` flag I get strange behavior: https://u.teknik.io/CgFdc.mp4

**Comment by budRich** [comment]
i hope most of these issues will get fixed in the new update.
