### ISSUE TITLE
[i3king] errors?

### ISSUE THREAD

**Issue by gmardom** [budlabs/i3ass#207]
### before anything else, try to reproduce the bug with the [wiki config](https://github.com/budlabs/i3ass/wiki/i3-config-example)

still occurs... (not relevant)

**Describe the bug**
This issue does not break the behavior of the `i3king` but script reports:
```
/usr/bin/i3king: line 359: unset: [-1]: bad array subscript
/usr/bin/i3king: line 360: unset: [-1]: bad array subscript
```
each time new window spawns included in DEFAULT rule.

**To Reproduce**
1. Run `i3king` with `i3king --verbose --config /path/to/minimal/config`
2. Spawn terminal with instance/role `auto`, eg: `i3term --autotile` using [i3term](https://github.com/budlabs/i3term)
3. Observe `i3king`'s output.

Minimal `i3king` config:
```
DEFAULT \
  class=(URxvt|XTerm|st-256color) instance=auto, \
  class=Xfce4-terminal role=auto, \
    floating enable
```

**Expected behavior**
`i3king` works as expected, but the errors pop up.

**Screenshots**

Full output after spawning the terminal:
```
i3king start
class:(URxvt|XTerm|st-256color):instance:auto:title:.*:window_type:.*:window_role:.*:
class:.*:instance:.*:title:.*:window_type:.*:window_role:.*:
/usr/bin/i3king: line 359: unset: [-1]: bad array subscript
/usr/bin/i3king: line 360: unset: [-1]: bad array subscript
/usr/bin/i3king: line 359: unset: [-1]: bad array subscript
/usr/bin/i3king: line 360: unset: [-1]: bad array subscript
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Distro: Arch btw

**Post the output of the command `i3ass`**
```
i3flip   | 0.105   | 2022-05-21 | /usr/bin/i3flip
i3fyra   | 1.4.2   | 2023-07-22 | /usr/bin/i3fyra
i3get    | 0.83    | 2022-07-19 | /usr/bin/i3get
i3gw     | 0.999   | 2022-05-21 | /usr/bin/i3gw
i3king   | 0.4.2   | 2023-07-13 | /usr/bin/i3king
i3Kornhe | 0.7     | 2023-07-22 | /usr/bin/i3Kornhe
i3list   | 0.53    | 2023-07-12 | /usr/bin/i3list
i3var    | 0.050   | 2022-05-21 | /usr/bin/i3var
i3viswiz | 0.56    | 2023-07-22 | /usr/bin/i3viswiz
i3zen    | 0.2     | 2023-07-29 | /usr/bin/i3zen

-------------------------------------------

i3 version 4.22 (2023-01-02) © 2009 Michael Stapelberg and contributors
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
GNU Awk 5.2.2, API 3.2, PMA Avon 8-g1, (GNU MPFR 4.2.0-p12, GNU MP 6.2.1)
xdotool version 3.20211022.1

-------------------------------------------
```

**Additional context**
Tried both release and `-git` versions available on aur.

**Comment by gmardom** [comment]
After short investigation it appears, that this happens only if DEFAULT rule is present.

Also when I change DEFAULT to GLOBAL similar issue pops up somewhere else:
```
/usr/bin/i3king: line 383: execute: bad array subscript
```

Without those, `i3king` has no other issues like that.

**Comment by budRich** [comment]
big thanks for reporting this. I will try to fix the issue tomorrow.

**Comment by budRich** [comment]
i think the problem is that the configuration has some typos:  

```
DEFAULT \
  class=(URxvt|XTerm|st-256color) instance=auto, \
  class=Xfce4-terminal role=auto, \
    floating enable
```

The syntax definition is like this:  

```
RULE
  COMMAND
```

So, RULE on line 1, COMMAND on line 2, with COMMAND indented.
Backslash can be used to escape newlines. The last `\` (and `,`) in the minimal default makes it invalid:  

```
DEFAULT class=(URxvt|XTerm|st-256color) instance=auto, class=Xfce4-terminal role=auto, floating enable
```

what we want:  

```
DEFAULT class=(URxvt|XTerm|st-256color) instance=auto, class=Xfce4-terminal role=auto
  floating enable
```

can be written like this:
```
DEFAULT \
  class=(URxvt|XTerm|st-256color) instance=auto, \
  class=Xfce4-terminal role=auto
    floating enable
```

---

I will try to catch these types of errors in the i3king parser, and print useful error messages. That fits perfect with the other patches to the next release which is about stricter commandline parsing.

**Comment by 1ntronaut** [comment]
@budRich 
Hi bud, I have too encountered this error some time ago. I assumed (incorrectly it seems now) that it was my own doing and kept editing the config for i3king until the error message no longer appeared. Admittedly, I find/found the syntax for i3king's config quite hard to grasp.

I _did_ discover that it was related to GLOBAL and DEFAULT, but couldn't make sense of it ; and eventually ended up with a significantly slimmed down config file, having removed the majority of my i3king rule statements.

Sorry for not reporting this.

> in other news: last night, I was writing another lengthy reply to your suggestions and work on i3ass... but accidentally killed my X session before submitting it ;p. Real busy with real life stuff right now.. but will reply to you in due time

**Comment by gmardom** [comment]
I'm glad that my inability to copy/paste config from i3term's readme helped in some way ;P

**Comment by budRich** [comment]
copy what i mean, not what i paste
