### ISSUE TITLE
[i3run] Will not windows move to empty workspace

### ISSUE THREAD

**Issue by vn-ki** [budlabs/i3ass#32]
I have this binding in my i3 config

```i3
bindsym $mod+Ctrl+f exec i3run -s -i "thunar" -e "thunar"
```

Suppose I move to an empty workspace, and the keys, it will open thunar for the first time correctly.
I press the keys again, it will hide thunar.
If I press again, I will be switched to nearest lower workspace and thunar will be shown.

This happens with empty workspaces only.

**Comment by budRich** [comment]
Thank @vn-ki for an excellent report, I will investigate this. I think it's an easy fix.

**Comment by budRich** [comment]
This issues should be fixed in the latest release (#33 ).

**Comment by vn-ki** [comment]
Now it is behaving weirdly. 

Whenever I press my keybindings (and I am in workspace 1, 2, or 3) it will take to workspace 4 and put thunar there.
If I am in a workspace 4 or above, it works without any problems. (even if workspace is empty)

**Comment by budRich** [comment]
that sounds really strange, i will take a look. I only tested quickly on workspace 1 and 2.
Also, what are the names of your wokspaces? could you paste the output of:  

`i3-msg -t get_workspaces`

**Comment by budRich** [comment]
i managed to reproduce this now, doesn't seem to have anything to do with workspace names, but the output could still be useful..

**Comment by vn-ki** [comment]
```
$  i3-msg -t get_workspaces


[{'focused': True,
  'name': '1',
  'num': 1,
  'output': 'eDP1',
  'rect': {'height': 741, 'width': 1366, 'x': 0, 'y': 27},
  'urgent': False,
  'visible': True},
 {'focused': False,
  'name': '3',
  'num': 3,
  'output': 'eDP1',
  'rect': {'height': 741, 'width': 1366, 'x': 0, 'y': 27},
  'urgent': False,
  'visible': False},
 {'focused': False,
  'name': '4',
  'num': 4,
  'output': 'eDP1',
  'rect': {'height': 741, 'width': 1366, 'x': 0, 'y': 27},
  'urgent': False,
  'visible': False}]

```

Also, thanks for your quick responses.

**Comment by budRich** [comment]
great. I think i have fixed it now. Yesterday when I applied the first fix, i added a new method to identify workspaces, and it currently coexist with the old one and there where some missmatching. But it should be fixed now, please try the latest release.  

I will refactor and clean up the code of `i3list` for the next release.

**Comment by vn-ki** [comment]
It's working perfectly now. Thanks.
