### ISSUE TITLE
[i3fyra] floating state toggled randomly for certain windows

### ISSUE THREAD

**Issue by mrcush** [budlabs/i3ass#38]
Everytime I reopen my laptop and enter a command into the terminal, it will pop out to floating to which I have to reset it back into its container.  After that it will be fine until I close my laptop and the screen shuts down and then I have to do it over again.  This seems to happen with other applications as well (sublime text) but not nearly as frequently.  Seems to need some sort of command to make the windows pop out to floating or something.  I saw in one of your videos that you had this same experience.  Wasn't sure if you had found a fix or know the reasoning behind it.

Thanks!

EDIT: Retested and it doesn't happen the first time I open terminal but it does happen randomly and always after I enter a command in

**Comment by budRich** [comment]
I have this popping issues with sublime when i apply a new theme with mondo, and very rarely otherwise. Not 100% sure whats causing it. I would guess that the window (sublime) recreates the window, and by doing so it triggers for_window in i3 (which defaults to floating enable in my and maybe you setup). 

Is there any particular program that usually cause the issue (f.i. htop, ranger or ncmpcpp). And last what for_windo rules have you set for the terminal.

Thanks for reporting. I have been very busy this last week with reality (moving) and is currently in the process of setting up a new workstation, but i will really try to fix i3ass/fyra for the new i3 version. Maybe these popping issues will be resolved or less frequent with the new i3 version.

**Comment by mrcush** [comment]
> I have this popping issues with sublime when i apply a new theme with mondo, and very rarely otherwise. Not 100% sure whats causing it. I would guess that the window (sublime) recreates the window, and by doing so it triggers for_window in i3 (which defaults to floating enable in my and maybe you setup).
> 
> Is there any particular program that usually cause the issue (f.i. htop, ranger or ncmpcpp). And last what for_windo rules have you set for the terminal.
> 
> Thanks for reporting. I have been very busy this last week with reality (moving) and is currently in the process of setting up a new workstation, but i will really try to fix i3ass/fyra for the new i3 version. Maybe these popping issues will be resolved or less frequent with the new i3 version.

No, no other program that I can see.  Also, ever since switching to Kitty from URxvt I haven't had this issue.  It seems to be dependent on the software doing as you said, calling for_window.  Here is a list of my for_window rules:

```
for_window [class="Sublime_text"] focus; exec --no-startup-id i3fyra -m A
for_window [class="Firefox"] focus; exec --no-startup-id i3fyra -m A
for_window [class="libreoffice"] focus; exec --no-startup-id i3fyra -m A
for_window [class="libreoffice-write"] focus; exec --no-startup-id i3fyra -m A
for_window [class="Soffice"] focus; exec --no-startup-id i3fyra -m D
for_window [class="Spacefm"] focus; exec --no-startup-id i3fyra -m B
for_window [class="Lxappearance"] focus; exec --no-startup-id i3fyra -m A
for_window [class="Xfce4-settings-manager"] focus; exec --no-startup-id i3fyra -m A
for_window [class="Blueberry.py"] focus; exec --no-startup-id i3fyra -m D
for_window [class="jetbrains-studio"] focus; exec --no-startup-id i3fyra -m A
for_window [class="Tor Browser"] focus; exec --no-startup-id i3fyra -m A
for_window [class="qBittorrent"] focus; exec --no-startup-id i3fyra -m A
for_window [class="Font-manager"] focus; exec --no-startup-id i3fyra -m A
for_window [class="Thunar"] focus; exec --no-startup-id i3fyra -m B
```

**Comment by mrcush** [comment]
Update: I was wrong about Kitty being excluded from this.  It is now popping out as well.

**Comment by budRich** [comment]
Sorry for the late reply.  @mrcush , i think this issue might be fixed in the latest release. If the issue is fixed, you can close this issue, otherwise I will if I haven't heard from you in a week.
