### ISSUE TITLE
#!/usr/bin/env bash issue

### ISSUE THREAD

**Issue by chrisdepas** [budlabs/i3ass#40]
Firstly, thanks for sharing. I've only used i3Kornhe so far, but it's exactly how it should be, great work.

Had one small issue with setup. The scripts all use `#!/usr/bin/env bash` to locate bash, but this wasn't symlinked on my machine (ubuntu 18.04 server) by default. 

It might be helpful to check /usr/bin/env in the installer, and warn the user. The installer might print the ln command, or ask to be run with sudo & then fix it automatically. I'm happy to add this and submit a PR. However, it's an easy fix for the user to do and will add clutter to the installer, so if you don't think this is worth adding please close this issue.

Thanks!

**Comment by budRich** [comment]
huh. I added this shebang with the hope it would become **more** portable. https://www.cyberciti.biz/tips/finding-bash-perl-python-portably-using-env.html . I have planned on getting a computer dedictated to ubuntu to be sure that everything works there too, currently i only test this on arch.

Regarding the issue and possible fix, i have to research this to find whats best. I bet that if i change it to `#!/bin/bash` (*that i used before*), it won't work on some other distro.

Solution might be to have different shebangs depending on the distro, it is not impossible to achieve with bashbud and makefile magic.

Thank for reporting, and sorry for the late reply.

**Comment by budRich** [comment]
the more i research this shebang stuff the less sure i am which one to use. I am leaning towards using `#!/bin/bash` again...

**Comment by budRich** [comment]
https://stackoverflow.com/questions/733824/how-to-run-a-shell-script-on-a-unix-console-or-mac-terminal/733901#733901
https://en.wikipedia.org/wiki/Shebang_(Unix)
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=906901#34

**Comment by chrisdepas** [comment]
Hey, sorry this reply took a year!

Thanks for taking the time to reply and to look into this. I posted this originally from a machine that started as Ubuntu server, which may have been why `/usr/bin/env` wasn't symlinked by default.

After posting this, I looked into it (and found some of the links you posted), it seems that `/usr/bin/env` is the way to go in terms of portability.
