### ISSUE TITLE
Does this work with i3-gaps? Getting syntax errors ...

### ISSUE THREAD

**Issue by ckp95** [budlabs/i3ass#41]
Hi, I'm trying to use i3viswiz with i3-gaps but I'm having some trouble. I added the commands to my i3 config file like this:

    bindsym $mod+Left exec --no-startup-id ~/.scripts/i3ass/i3viswiz left
    bindsym $mod+Down exec --no-startup-id ~/.scripts/i3ass/i3viswiz down
    bindsym $mod+Up exec --no-startup-id ~/.scripts/i3ass/i3viswiz up
    bindsym $mod+Right exec --no-startup-id ~/.scripts/i3ass/i3viswiz right

but when I use the keyboard command, nothing happens. I tried running the script just straight from the terminal and I get these syntax errors:

    ckp95@ckp95-desktop:~/.scripts/i3ass$ ./i3viswiz left
    awk: line 6: syntax error at or near [
    awk: line 17: syntax error at or near if
    awk: line 18: syntax error at or near [
    awk: line 20: syntax error at or near [
    awk: line 25: syntax error at or near [
    awk: line 6: syntax error at or near [
    awk: line 17: syntax error at or near if
    awk: line 18: syntax error at or near [
    awk: line 20: syntax error at or near [
    awk: line 25: syntax error at or near [

I can run the help command `./i3viswiz -h` and it prints the documentation just fine, and I can run the version command `./i3viswiz -v` and it gives 

    i3viswiz - version: 0.018
    updated: 2018-06-30 by budRich

I haven't checked all of the other scripts yet but it does seem like i3get is working. e.g. I can do

    ./i3get -i gedit -r tcidnmwafov
    *Untitled Document 1 - gedit
    Gedit
    gedit
    27263108
    94713688104640
    1
    false
    auto_off

and that works. But i3viswiz is having problems ... :(

Any idea what to do? This is my i3 -version:

    i3 version 4.16-86-g1fd20ce7 (2018-12-14, branch "gaps-next") © 2009 Michael Stapelberg and contributors

**Comment by budRich** [comment]
Some of the scripts (i3get) should work on **gaps**, others doesn't work. I don't use gaps, and will not make any adaptations to the scripts for it, maybe later, probably not.
