### ISSUE TITLE
[i3frya] containerhide command showing errors in terminal and not hiding window.

### ISSUE THREAD

**Issue by APotOfSoup** [budlabs/i3ass#47]
I've been slowly trying to implement i3ass and had been having some issues with containers not hiding properly. I did a lot of testing to try and figure it out with tons of `echo test` and `echo $var`. I am using i3run and it was behaving weirdly from what i had expected after watching the majority of your youtube lets linux.

i3run was unable to hide windows handled by i3fyra. i3run would hide windows unhandled and floating. i3run would then return them from the scratch pad and they wouldn't be floating anymore ( i3list issue about the TWF key not being set ). I did some debugging to try and fix it and i believe that the problem with the handled containers in this code.
`  elif [[ -n ${__o[hide]:-} ]]; then
    cmd=containerhide
    target="${__o[hide]}"`
or this code
`    --hide       | -z ) __o[hide]=1 ;; `
I choose to change the former to
`  elif [[ -n ${__o[hide]:-} ]]; then
    cmd=containerhide
    target="$1"`
and got it to work.

I am not positive that this is the exact thing causing my issues but I'm currently testing with the changes I've done to i3fyra and i3list and it's seems to be working as intended now. I may have changed some other things then this and can attach my current copy of your code that I have edited to resolve my issues.

You may have even caught these already but I'm posting in case it might help someone. Thanks for the awesome layout.

**Comment by budRich** [comment]
highly appreciate your report, investigation and fix. I have more or less not had anyone looking at the code before, so if you have any constructive criticism about it, i listen. I will, as i said in the other issue, make some tests with your fixes, and upload a new release with them implemented later today. thanks.
