### ISSUE TITLE
[i3get] --print is not always printing what it should..

### ISSUE THREAD

**Issue by budRich** [budlabs/i3ass#54]
Originally posted by @APotOfSoup in #51 : 

I was just testing **i3get and I think it might be broken with certain -r options like f.** I'm just about to investigate that haha I am pretty positive I have the current i3get that you put up recently.

**Comment by APotOfSoup** [comment]
From the tiny bit of time I got to test it seems like it's actually broken when searching for specific container ids. I did something simple like a normal i3get with default options only one single terminal open. It returns the proper container Id. Now running i3get -n 'id-we-just-got' should return the exact same id but it points to something else now. 

I haven't even looked into what might cause it yet but hopefully that helps. I'll possiblely be able to test more tonight

**Comment by budRich** [comment]
i think this issue is fixed now with this PR: https://github.com/i3ass-dev/i3get/pull/1

as you might have noticed i have moved a lot of stuff around, and will not merge this into the master of this repo (and create a new release) just yet. But you can test it if you want by, using https://github.com/i3ass-dev/i3get/blob/dev/program.sh  

I have planned to write a little i3ass hacking guide, to describe how all the files, repos and such are organized and how to easiest test and contribute to the code.

Thanks a million, for using, testing and reporting issues!
