### ISSUE TITLE
[i3frya] Using for_window rule to set floating disabled while no i3fyra layouts are active causes i3fyra layout to start shifted over

### ISSUE THREAD

**Issue by APotOfSoup** [budlabs/i3ass#58]
Hey, you may already have a better solution to this but I have been running into some funny results when loading my terminals in the wrong order.

I haven't switched to your new way to float with ipc yet but I think this is unrelated.

I had a `for_window [instance="tiledterminal"], floating disabled` line for setting my terminals like I showed you in the --force issue thread.

It all works great when I have and active i3fyra layout already running.

I found though that if I open a tiled terminal before opening my first application with a window rule to move it to a specific container, my entire i3fyra layout would start building in a split with the first tiled term taking up the entire left side of my screen.

I know that just opening these applications in the right order would mean this would never happen. You might even have a command or something baked in i3ass to fix this but i haven't found it.

If you have something that works for this situation I'd like to hear your thoughts on this. I know that I could auto launch a program that goes to a i3fyra container on startup but I want my computer to open with just my status bar and my wallpaper when I first log in.

The solution I am currently doing instead of using floating disable in my for_window 's I wrote a script that I run on my tiled term in the for_window for those instances. In that script I look for `i3list[LVI]` and if it is blank I run `i3fyra -a` to force a layout to open when it first tiles. If the `i3list[LVI]` is anything else I run an `i3-msg -q [con_id=$(i3get)] floating disabled` so that it ends up in my focused i3fyra container and not the default container which `i3fyra -a` does. I do a focus before I run my script so that the window that is active is the one running this script, I believe my current script is broken if I don't.

If this makes any sense, I'd love to hear your thoughts or fixes. I am currently not on the computer that I made the script on and will post my exact for_window and script when I am able.

Thanks again!
 
P.S. I would like to PM about some other thought I've had to get some insight but I don't know if that is possible on git.

P.P.S I also couldn't figure out how to post a issue on your new repo set up. I dont know if I am missing something or its disabled.

**Comment by APotOfSoup** [comment]
for_window [instance="tiledterm"], focus; exec --no-startup-id i3fyrst
[i3fyrst.txt](https://github.com/budlabs/i3ass/files/2896535/i3fyrst.txt)

**Comment by budRich** [comment]
the solution to all for_window rule problems is to stop using for_window and start using **i3king**. Long live the king!
