### ISSUE TITLE
[i3fyra] workspace bug

### ISSUE THREAD

**Issue by yuceltoluyag** [budlabs/i3ass#6]
Hi I want to use the script but my workspaces do not work as expected
As you can see in the video, there are only two places to go and sometimes it goes to the work area named X and when I restart it it gets better

https://youtu.be/jFBsdNIW2Ic

**Comment by budRich** [comment]
hello, sorry for the very late reply. I am making a major rewrite of all the i3ass scripts, and i hope this issue will be resolved in the update, but I keep it open in case it persists. Then i will investigate it further.
