### ISSUE TITLE
Showing a hidden container makes the window inside it larger.

### ISSUE THREAD

**Issue by ghost** [budlabs/i3ass#64]
Not sure how to explain this, but when showing a previously hidden container, the window within it will be larger than what I had set in my exec.
If this is a mistake on my end please do not hestitate to tell me haha.

example; https://0x0.st/zcpq.gif

My config for hidden shit; 
bindsym $mod+a 					exec i3fyra "AC=100 BD=250"; exec i3fyra --show A
bindsym $mod+shift+a 			exec i3fyra "AC=100"; exec i3fyra --hide A

**Comment by alechstong** [comment]
This is happening to me as well. When I hide/show A or C, A will become larger. When I hide/show B or D, B will become larger.

I tested it out. When I hide then show A (by executing `i3fyra -m u` twice), the AC Split value will increase by 24. Here are the i3loist values of 4 rounds of toggle:

i3list[SAC]=539  
i3list[SAC]=563
i3list[SAC]=587
i3list[SAC]=611

**Comment by fwanky** [comment]
I found, somewhat of a "FIX" for this. 
What I added was another exec on the same line, for i3fyra to exec the desired size of the window
so if I do this; as the issue persists with i3run too, it will fix it. 
$bsym $mod+F4				  $E i3run -i music -e 'urxvt -name music -e mocp'; $E i3fyra -l "BD=252"
($E as in exec)

**Comment by budRich** [comment]
i think this is fixed now, please let me know if it isn't.
