### ISSUE TITLE
[i3Fyra] Sending something to container via it's name

### ISSUE THREAD

**Issue by ghost** [budlabs/i3ass#69]
Is there some way for me to send certain things to containers via their names? 
Say, if I were to open a firefox image upload window, the class and instance would be the same as the firefox window, so what i'm asking, is it possible to send something to a certain container via the name of the actual window?

For example, file uploader will always be called "File upload".

**Comment by budRich** [comment]
I use this method myself:
Some of my applications could be considered "main applications" (texteditor, browser, filemanager etc). What I do is to add the `-x` option in i3run to rename the class or instance name of the window when it is created, and have a rule matching this renamed class. Then all other windows that are created by the applications will either default to the default floating rule or another rule.

`i3run --rename sublime_text --instance sublime_main --command subl`

the command above would look for a window with the instance name sublime_main, if that is not found it will execute `subl` and wait for a window with the instance name sublime_text and rename that instance to sublime_main.

Then I have a rule matching the sublime_main instance and putting it in a container, all other windows that are created by sublime, will not occupy the container and instead become floating.

But yes, you can also use the title.

:)
