### ISSUE TITLE
[i3fyra] Not functioning properly when used outside of i3fyra workspace.

### ISSUE THREAD

**Issue by almos98** [budlabs/i3ass#70]
I'm experiencing this after I replace the default move commands with `exec --no-startup-id exec i3fyra -m <direction>`, where `<direction>` is the l/d/u/r accordingly. 

It seems to work fine when in the i3fyra workspace, but if I try to use it in other workspaces it will move that window to the bottom-right container in the i3fyra workspace, no matter the direction.

**Comment by deagle-zlt** [comment]
in i3 4.16.1 (2019-01-27) i3fyra -m <direction> don't work.
```
ERROR: Given criteria don't match a window
[ERROR] no matching window
```

**Comment by budRich** [comment]
I think this is fixed now.
