### ISSUE TITLE
Wrong variable name in makefile

### ISSUE THREAD

**Issue by dionisiovj** [budlabs/i3ass#71]
Hej. In the makefile, you mistyped a variable name (`INSMAN` instead of `INSTMAN`). The error happens twice. It has as a consequence that the man pages aren't removed when doing `make uninstall`.

It is a very minor thing but you know... For the sake of completeness.

Jag älskar dina Videos!

**Comment by budRich** [comment]
the makefile has been rewritten, thanks for reporting this. tack för kärleken. ha en bra dag.
