### ISSUE TITLE
i3fyra containers B and D don't work 

### ISSUE THREAD

**Issue by SAVsciense** [budlabs/i3ass#72]
I know that this bug #39 has been fixed, but I have the exact same problem:
i3fyra -m (l/f) and (left/fight):

[ERROR] no matching window.
ERROR: Given criteria don't match a window
[ERROR] no matching window.
ERROR: Given criteria don't match a window

i3fyra -m (A/B/C/D) - everything works well

i3fyra - version: 0.551
updated: 2019-02-19 by budRich

i3 version 4.16 (2018-11-04) © 2009 Michael Stapelberg and contributors

i3ass - version: 2019.03.14.5
updated: 2019-03-14 by budRich

script   | version
------------------
i3flip   | 0.052
i3fyra   | 0.551
i3get    | 0.35
i3gw     | 0.174
i3Kornhe | 0.033
i3list   | 0.045
i3menu   | 0.02
i3run    | 0.041
i3var    | 0.033
i3viswiz | 0.044

dependencies:
bash     [INSTALLED]
gawk     [INSTALLED]
i3       [INSTALLED]
rofi     [INSTALLED]
sed      [INSTALLED]
xdotool  [INSTALLED]

**Comment by budRich** [comment]
is this still an issue?

**Comment by budRich** [comment]
i hope it isn't, please let me know if it still is a problem. I have found an issue where things might get weired on a empty workspace (i will write the issue after this comment..). that might be related to this and other related things.. have a great day!
