### ISSUE TITLE
[i3fyra]change foucus and tab swithch function not working with i3fyra

### ISSUE THREAD

**Issue by henryzxb** [budlabs/i3ass#74]
i3 version 4.16.1 (2019-01-27)
i3fyra - version: 0.551

When i use "i3fyra -f l/d/u/r" command to change window focus,nothing happened;
and "i3fyra -t r/l" command also not working.
Is that anything i dismiss to make it run ?

**Comment by budRich** [comment]
sorry for the late reply, i3fyra -f and i3fyra -t are deprecated. use i3viswiz l/d/u/r instead, and i3flip next/prev
