### ISSUE TITLE
window focus remains same but input goes to container A after exiting dmenu

### ISSUE THREAD

**Issue by UddipakBhuyan** [budlabs/i3ass#77]
Hey budrich,
If I am in the i3fyra workspace and execute dmenu but quit it without starting any program, the focus window remains the one which it was previously but the keyboard input always goes to container A(if it exists).
If A doesn't exist input goes to container C. If C doesn't exist it goes to D.

**Comment by budRich** [comment]
This is strange, could you try the new version of i3ass and report if this behavior persist?
Also, where you using i3menu, or just dmenu?

**Comment by UddipakBhuyan** [comment]
Sorry I have stopped using i3ass so I can't reproduce it. Also I was using just dmenu as far as I remember. You can close this issue if you think this behaviour doesn't happen on the latest version.

**Comment by budRich** [comment]
thanks for the report! Have a great day.
