### ISSUE TITLE
when starting i3fyra i get the error Failed to find appropriate t c

### ISSUE THREAD

**Issue by overlock1** [budlabs/i3ass#79]
hello bud, i'm loving i3ass but for about 3 days now i'm having some problems with i3ass, i3fyra when starting shows me this error, and i reload on i3 and add the decoration then restart again gives this error but it works , i3run does not change the name of the application,i'm using archlinux with i3-wm without gaps,I installed the i3ass from aur.

**Comment by budRich** [comment]
I look into it, i have planned making the "init/start" of i3fyra better, this is a good reason to do so.
Can you post the exact commands (both i3fyra and i3run) and the full error messages / (expected result with i3run)
