### ISSUE TITLE
[FR] document i3viswiz code

### ISSUE THREAD

**Issue by laur89** [budlabs/i3ass#81]
I don't really speak awk, and `i3viswiz` is too much of a mystery at this point.
But the functionality is superb.

Full disclosure, I'm searching for better ideas for similar python implementation I've been using for some years now: [gist](https://gist.github.com/laur89/ea7d92ef6d3f1421b1db8f998db76fde#file-i3-cycle-exclude-tabs-py)

**Comment by budRich** [comment]
I agree, i remember last time I updated i3ass, I could barely understand this script myself. I will try to improve it in the next update (soon ;)

**Comment by budRich** [comment]
I made a short video walkthrough of the AWK part of the script. It's unlisted on my channel but you can find it by following the hyperlink below:  
https://youtu.be/3Rwtx47j5Hg

**Comment by laur89** [comment]
> 2h

Great effort! Will have a watch next week when I have more time in my hands.

**Comment by budRich** [comment]
I hope the version of i3viswiz currently shipped with i3ass is easier to interpret.
